const cities =  [
    "Ahmednagar",
    "Akola",
    "Akot",
    "Amalner",
    "Ambejogai",
    "Amravati",
    "Anjangaon",
    "Arvi",
    "Aurangabad",
    "Bhiwandi",
    "Dhule",
    "Kalyan-Dombivali",
    "Ichalkaranji",
    "Kalyan-Dombivali",
    "Kolhapur",
    "Latur",
    "Malegaon",
    "Mumbai",
    "Nagpur",
    "Nanded",
    "Nandurbar",
    "Nashik",
    "Osmanabad",
    "Parbhani",
    "Pimpri-Chinchwad",
    "Pune",
    "Sangli",
    "Satara",
    "Solapur",
    "Thane",
    "Ulhasnagar",
    "Vasai-Virar",
    "Virar",
    "Yavatmal",
    "Alibag",
    "Ambernath",
    "Ambajogai",
    "Ambarnath",
    "Ankleshwar",
    "Ausa",
    "Badlapur",
    "Balapur",
    "Baramati",
    "Barshi",
    "Beed",
    "Bhandara",
    "Bhingar",
    "Bhiwandi",
    "Bhusawal",
    "Bid",
    "Buldhana",
    "Chalisgaon",
    "Chandrapur",
    "Chikhli",
    "Chiplun",
    "Chopda",
    "Dahanu",
    "Daund",
    "Dehu",
    "Deolali",
    "Deulgaon Raja",
    "Dharangaon",
    "Dharmabad",
    "Dhule",
    "Digdoh",
    "Diglur",
    "Dombivli",
    "Durgapur",
    "Gadchiroli",
    "Gangakhed",
    "Georai",
    "Ghatanji",
    "Ghoti",
    "Gondia",
    "Goregaon",
    "Guhagar",
    "Hadgaon",
    "Hinganghat",
    "Hingoli",
    "Hinjilikatu",
    "Ichalkaranji",
    "Igatpuri",
    "Indapur",
    "Jalgaon",
    "Jalna",
    "Jamkhed",
    "Jamner",
    "Jath",
    "Jaysingpur",
    "Jintur",
    "Kagal",
    "Kalyan",
    "Karad",
    "Karanja",
    "Khadki",
    "Khamgaon",
    "Khed",
    "Kinwat",
    "Kopargaon",
    "Kudal",
    "Kurduvadi",
    "Lanja",
    "Lasalgaon",
    "Latur",
    "Lonar",
    "Lonavale",
    "Mahabaleshwar",
    "Mahad",
    "Mahuli",
    "Malegaon",
    "Malvan",
    "Manchar",
    "Mangalvedhe",
    "Mangrulpir",
    "Manmad",
    "Manwath",
    "Mhaswad",
    "Miraj",
    "Morshi",
    "Mukhed",
    "Mul",
    "Mumbai",
    "Murtijapur",
    "Nachane",
    "Nagbhid",
    "Nagpur",
    "Nalasopara",
    "Nandgaon",
    "Nanded",
    "Nandgaon",
    "Nandura",
    "Nashik",
    "Navi Mumbai",
    "Nawapur",
    "Nilanga",
    "Osmanabad",
    "Pachora",
    "Pandharkaoda",
    "Pandharpur",
    "Panhala",
    "Paratwada",
    "Pauni",
    "Pen",
    "Phaltan",
    "Pimpalner",
    "Pimpri",
    "Pune",
    "Purna",
    "Pusad",
    "Radhanagari",
    "Rahimatpur",
    "Rahuri",
    "Raigad",
    "Rajapur",
    "Rajura",
    "Ramtek",
    "Ratnagiri",
    "Raver",
    "Risod",
    "Sailu",
    "Sangamner",
    "Sangli",
    "Sangole",
    "Sasvad",
    "Satana",
    "Satara",
    "Savantvadi",
    "Savda",
    "Sawantwadi",
    "Shahada",
    "Shahapur",
    "Shegaon",
    "Shendurjana",
    "Shirdi",
    "Shirala",
    "Shirpur-Warwade",
    "Shirur",
    "Shrigonda",
    "Shrirampur",
    "Shrivardhan",
    "Sillod",
    "Sinnar",
    "Solapur",
    "Soyagaon",
    "Talegaon Dabhade",
    "Talode",
    "Tasgaon",
    "Tathavade",
    "Thane",
    "Tirora",
    "Tuljapur",
    "Tumsar",
    "Udgir",
    "Umarkhed",
    "Umred",
    "Uran",
    "Vaduj",
    "Vaijapur",
    "Vasai",
    "Vita",
    "Wadi",
    "Wai",
    "Wani",
    "Wardha",
    "Warora",
    "Warud",
    "Washim",
    "Yavatmal",
    "Yawal",
    "Yeola",
    "New York City",
  "Buffalo",
  "Rochester",
  "Yonkers",
  "Syracuse",
  "Albany",
  "New Rochelle",
  "Mount Vernon",
  // California
  "Los Angeles",
  "San Diego",
  "San Francisco",
  "San Jose",
  "Fresno",
  "Sacramento",
  "Long Beach",
  "Oakland",
  // Texas
  "Houston",
  "San Antonio",
  "Dallas",
  "Austin",
  "Fort Worth",
  "El Paso",
  "Arlington",
  "Corpus Christi",
  // Florida
  "Jacksonville",
  "Miami",
  "Tampa",
  "Orlando",
  "St. Petersburg",
  "Hialeah",
  "Tallahassee",
  "Fort Lauderdale",
  // Illinois
  "Chicago",
  "Aurora",
  "Rockford",
  "Joliet",
  "Naperville",
  "Springfield",
  "Peoria",
  "Elgin",
  // Pennsylvania
  "Philadelphia",
  "Pittsburgh",
  "Allentown",
  "Erie",
  "Reading",
  "Scranton",
  "Bethlehem",
  "Lancaster",
  // Ohio
  "Columbus",
  "Cleveland",
  "Cincinnati",
  "Toledo",
  "Akron",
  "Dayton",
  "Parma",
  "Canton",
  // Georgia
  "Atlanta",
  "Augusta",
  "Columbus",
  "Macon",
  "Savannah",
  "Athens",
  "Sandy Springs",
  "Roswell",
  // North Carolina
  "Charlotte",
  "Raleigh",
  "Greensboro",
  "Durham",
  "Winston-Salem",
  "Fayetteville",
  "Cary",
  "Wilmington",
  // Michigan
  "Detroit",
  "Grand Rapids",
  "Warren",
  "Sterling Heights",
  "Lansing",
  "Ann Arbor",
  "Flint",
  "Dearborn",
  // New Jersey
  "Newark",
  "Jersey City",
  "Paterson",
  "Elizabeth",
  "Edison",
  "Woodbridge",
  "Lakewood",
  "Toms River",
  // Virginia
  "Virginia Beach",
  "Norfolk",
  "Chesapeake",
  "Richmond",
  "Arlington",
  "Newport News",
  "Alexandria",
  "Hampton",
  // Washington
  "Seattle",
  "Spokane",
  "Tacoma",
  "Vancouver",
  "Bellevue",
  "Kent",
  "Everett",
  "Renton",
  // Massachusetts
  "Boston",
  "Worcester",
  "Springfield",
  "Lowell",
  "Cambridge",
  "New Bedford",
  "Brockton",
  "Quincy",
  // Arizona
  "Phoenix",
  "Tucson",
  "Mesa",
  "Chandler",
  "Glendale",
  "Scottsdale",
  "Gilbert",
  "Tempe",
  // Tennessee
  "Nashville",
  "Memphis",
  "Knoxville",
  "Chattanooga",
  "Clarksville",
  "Murfreesboro",
  "Franklin",
  "Jackson",
  // Indiana
  "Indianapolis",
  "Fort Wayne",
  "Evansville",
  "South Bend",
  "Carmel",
  "Bloomington",
  "Fishers",
  "Hammond",
  // Missouri
  "Kansas City",
  "St. Louis",
  "Springfield",
  "Independence",
  "Columbia",
  "Lee's Summit",
  "O'Fallon",
  "St. Joseph",
  // Maryland
  "Baltimore",
  "Frederick",
  "Rockville",
  "Gaithersburg",
  "Bowie",
  "Hagerstown",
  "Annapolis",
  "College Park",
  // Wisconsin
  "Milwaukee",
  "Madison",
  "Green Bay",
  "Kenosha",
  "Racine",
  "Appleton",
  "Waukesha",
  "Oshkosh",
  // Colorado
  "Denver",
  "Colorado Springs",
  "Aurora",
  "Fort Collins",
  "Lakewood",
  "Thornton",
  "Arvada",
  "Westminster",
  // Minnesota
  "Minneapolis",
  "St. Paul",
  "Rochester",
  "Duluth",
  "Bloomington",
  "Brooklyn Park",
  "Plymouth",
  "St. Cloud",
  // South Carolina
  "Columbia",
  "Charleston",
  "North Charleston",
  "Mount Pleasant",
  "Rock Hill",
  "Greenville",
  "Summerville",
  "Sumter",
  // Alabama
  "Birmingham",
  "Montgomery",
  "Mobile",
  "Huntsville",
  "Tuscaloosa",
  "Hoover",
  "Dothan",
  "Auburn",
  // Louisiana
  "New Orleans",
  "Baton Rouge",
  "Shreveport",
  "Lafayette",
  "Lake Charles",
  "Kenner",
  "Bossier City",
  "Monroe",
  // Kentucky
  "Louisville",
  "Lexington",
  "Bowling Green",
  "Owensboro",
  "Covington",
  "Hopkinsville",
  "Richmond",
  "Florence",
  // Oregon
  "Portland",
  "Salem",
  "Eugene",
  "Gresham",
  "Hillsboro",
  "Beaverton",
  "Bend",
  "Medford",
  // Oklahoma
  "Oklahoma City",
  "Tulsa",
  "Norman",
  "Broken Arrow",
  "Lawton",
  "Edmond",
  "Moore",
  "Midwest City",
  // Connecticut
  "Bridgeport",
  "New Haven",
  "Stamford",
  "Hartford",
  "Waterbury",
  "Norwalk",
  "Danbury",
  "New Britain",
  // Iowa
  "Des Moines",
  "Cedar Rapids",
  "Davenport",
  "Sioux City",
  "Iowa City",
  "Waterloo",
  "Council Bluffs",
  "Ames",
  // Mississippi
  "Jackson",
  "Gulfport",
  "Southaven",
  "Hattiesburg",
  "Biloxi",
  "Meridian",
  "Tupelo",
  "Greenville",
  // Arkansas
  "Little Rock",
  "Fort Smith",
  "Fayetteville",
  "Springdale",
  "Jonesboro",
  "North Little Rock",
  "Conway",
  "Rogers",
  ];
  